### ISSUE TITLE
Harmony support in Revoke.cash

### ISSUE THREAD

**Issue by rkalis** [harmony-one/bounties#116]
# Description 
Implement Harmony support in Revoke.cash, allowing Harmony users to revoke their token approvals.

## Context
Token allowances are integral to DeFi, but can be dangerous if left unchecked (see https://kalis.me/unlimited-erc20-allowances). This is why I developed Revoke.cash for Ethereum, a dashboard that allows you to inspect, revoke and update your allowances.

Recently I've worked on adding more chain support to the app, and after talking with Leo from Harmony, we've agreed on a bounty to support the Harmony integration.

# Acceptance Criteria
* [ ] Deployment of Harmony support on the Revoke.cash domain

# Reward
$5k USD in ONE tokens.

**Comment by grassr00t** [comment]
This bounty is approved. [Revoke.cash](https://revoke.cash/) is a popular and trusted service for users to revoke their approval of tokens, to avoid potential security risk.

**Comment by LeoHChen** [comment]
This bounty is approved. [Revoke.cash](https://revoke.cash/) is a popular and trusted service for users to revoke their approval of tokens, to avoid potential security risk.

**Comment by developerfred** [comment]
@LeoHChen can i work on this bounty?

**Comment by rkalis** [comment]
For reference: the work for this bounty has been done already, it just needs to get deployed together with some additional changes. The bounty issue is so that there's a public record of the process.

**Comment by LeoHChen** [comment]
https://twitter.com/RevokeCash/status/1518714507564101635?s=20&t=b9nyIdZM_Q4gKbMyzUmstA
