### ISSUE TITLE
Harmony Tap to Pay with multi-sign wallet

### ISSUE THREAD

**Issue by DylanCkawalec** [harmony-one/bounties#60]
# Description
This Application will live on a mobile **Android/iPhone** or **smartwatch** will be a new gateway for the public to trade digital assets in person using a simple to use, mobile fiat bridge. With the tap of a phone, the two devices that are in range to accept payments will sense the radius of the transfer using a smart code that both parties share before the transfer begins. This will open the MultiSignature wallet that harmony has already created, but create a way to physically transfer funds from Party 1's Wallet to Party 2's wallet, in person. Gift your friends or family instantly with **Harmony's Tap and pay**. 

## Context
There's many vendors who are using the debit tap to pay systems across all major retailers. It's become so popular, that many people would like to do the same thing with applications like Venmo, PayPal and other such payment bridges with simple 2 factor authentication. Most applications do not have this kind of tap to pay for in person meetings or gatherings. If someone wanted to send money your way, they need your **email**, your **name** or even your **number**. 

This application **doesn't need any personal information** to trade, it's all public on the harmony blockchain and the transactions can be seen on the harmony's block explorer. All you do, is open the application on your smartwatch or phone, place the two devices that are ready to pair near one another, and enter the code to activate the transfer from $ONE wallet to the other. Then you're done! 

This is important, because usability factors are missing in the crypto space. Not only is it a product of harmony's, but it is the least expensive and fastest transfer of money over any mobile device. Utilizing the blockchain and an **electronic commerce** together. 

# Acceptance Criteria
* [ ] **Mobile Application development** (+) Integrate multi-signature wallet to live inside a mobile device. 
* [ ] Bluetooth enabled services for payment gateway parameter tracing, *an understanding of contactless payment systems*(+)
* [ ] Peer-to-peer payment recognition & 2FA enabled signature to transfer funds from Harmony's wallet
* [ ] JSON RPC smart contract experience ; establish a connection to the *Harmony Web 1Wallet*. 
* [ ] Oracle chain to connect data from the web to enable interaction through a mobile web3 interface. (+) 
* [ ] "Dapp Browser enabled"(+)
* [ ] Javascript interaction - UI/UX to accept and decline transfers from wallet. 
      * [ ] enabled systems that allow the application to place public wallet addresses inside recipient field
* [ ] 2FA UI
     * [ ] single harmony ONE token bridge for easy usability of the ONE tokens. 
          * [ ] Enable Harmony gas fee's to send payment. 
# Reward
TBD

# resources
**Dapp *Browser* Programmability for integration with the trust wallet browser** >> https://developer.trustwallet.com/
**1 Web Wallet, seemless user interface and interaction with web wallet**https://1wallet.crazy.one/wallets

**Comment by Estelle544** [comment]
I downloaded a wallet like you explained. Thank you for the reminder.
