### ISSUE TITLE
Harmony Validator Installer / Launchpad / Management Interface *

### ISSUE THREAD

**Issue by DylanCkawalec** [harmony-one/bounties#61]
# Description
## You provide the validator node server:
We’ll help you create, configure & manage your node from the first steps. Any provider running an Ubuntu 20.04LTS Server to run a Harmony Validator Server Node will be compatible with the application.
[Watch this Demo Video](https://www.youtube.com/watch?v=ydvMXFDrHwg&t=9s)

You own your node, you own your private data. The application will utilize harmony core files directly and private information will not be stored in the application data.

The application is designed to loads Harmony's software (Binary: Harmony CLI updates), and pulls in most recent database for use. 

## We will provide software to setup and manage your node:
On Software Launch:
- Application will install harmony if it's not present
    - Will download all harmony files
    - Will setup all necessary folders
    - Will reclone databases for shard 0 & the shard # in your config file
    - After installation of harmony the only manual step is loading or creating your BLS Key & Pass files
- Application will load a scoreboard of information and a menu of tools
    - Common daily management tasks at your fingertips without remembering long strings of code

#This application should do the following
- Display a scoreboard of information including:
    - Validator address, Hostname, IP, Harmony Service Status, Epoch Signing %, Logged in Username, Harmony directory
- Display a tools menu to perform the following tasks:
    - Check the Harmony service statistics
    - Display active BLS keys
    - Display any Harmony ONE wallet balance
    - Collect pending validator rewards on main-net & test-net
    - Start/Stop/Restart the Harmony service
    - Run Updates on Harmony binary software packages
    - Run Updates for the Ubuntu Operating System
    - Reboot your Harmony Validator Node Server

# Context
Currently there's a very high learning curve to install a harmony node that's only useful when you need to configure a brand new server. For most people, this is a long and difficult process full of many notes that need to be refined and recycled.

Cut down the time it takes to setup the harmony validator software on a VPS cloud server and provide a toolset to assist with daily management tasks. With proper development further levels of this project could include a remote gui or website for control of your nodes.

Eventually the community will have to be fully independent to run the network. The core team has a plan to hand over the entire network to the community. If we have validators drop off the face of the earth with no one around to help, this is the software that will help full-fill.

To add, the daily management becomes tiring, and this application will take away a lot of those time consuming problems with a couple of keystrokes. 

**Most common questions this application resolves - by enforcing best practices for validators.** 

**How do I even set up a validator !? How much time does it take to set up a validator? Do I need a user account? How do I use SSH keys to log in and run my validator or to manage my node? Why should I use digital ocean over provider X,Y,Z? How do I use extra storage volume for validator?** 

# Acceptance Criteria for continued development
* [ ] Develop applications in python
* [ ] First application will guide users through installation of Harmony Validator Software
* [ ] Create intuitive prompts to automatically complete setup with user
* [ ] Script setup of node
* [ ] Utilize best security practices to harden the network
* [ ] Convert harmony commands to a menu driven application
* [ ] Menu to cover most common daily tasks
* [ ] Create Scoreboard of Frequently used information
* [ ] Utilize compatibility with Auto-bidder for wallet password storage
* [ ] Proper documentation and continuous updates

# Reward
$2000 equivalent in ONE tokens.

**Comment by patrickmogul** [comment]
Hello, I'm accepting the work on this bounty.

**Comment by jacksteroo** [comment]
Note that there is a difference between a (registered & elected) Validator node, vs. a Full node (or fully-sync'ed node).  A Full node can have all the elements of being a Validator-ready node, with BLS keys, and is fully sync'ed up to the latest block height.  

Sounds like this bounty comes with nearly all the tooling necessary to create a Full node which can be turned into a Validator node (menu-driven terminal software, auto-bidder, setup scripts, etc.)

**Comment by patrickmogul** [comment]
Hello @jacksteroo 

I've taken the time to split the "installer" portion of this off into it's own repository, setup 3 different installation paths:

Regular Validator Node Setup - w/ option to restore wallet for registered/elected validators
Full Node Setup - Sets up harmony files and databases, leaves the wallet untouched, for fully synced nodes
Manual Setup - Choose y/n to do each step in the process to give full control

Tomorrow I will take time to make adjustments to verify the combo Menu Application & Installer package also works well for Full Node Non-Validating operators.

Thanks,
Patrick

**Comment by jacksteroo** [comment]
@patrickmogul curious to know where we are on this?

**Comment by DylanCkawalec** [comment]
@jacksteroo I believe there is now a UI that can be interacted with. When will the gitcoin bounty be posted so @patrickmogul can commit it?

**Comment by patrickmogul** [comment]
Hello @jacksteroo yes we have been waiting for the gitcoin posting as advised by the dev captains, let us know when we're ready to proceed, thanks!

**Comment by givp** [comment]
Winner selected. Congrats and thanks!

**Comment by DylanCkawalec** [comment]
https://github.com/easy-node-one/validatortoolbox
