### ISSUE TITLE
Migrate Aragon to Harmony

### ISSUE THREAD

**Issue by givp** [harmony-one/bounties#74]
# Description
Aragon is a framework for launching and managing Decentralized Autonomous Organizations. This bounty requires the migration and deployment of Aragon on the Harmony blockchain. 

## Context
Harmony is planning to launch several DAOs in the coming months to help its community. Aragon is a mature DAO framework that will allow Harmony and the community to easily launch and manage various initiatives.

Aragon: [https://aragon.org](https://aragon.org)
Rinkeby demo: [https://rinkeby.client.aragon.org/#/](https://rinkeby.client.aragon.org/#/)

# Acceptance Criteria
* A fully functional demo on Harmony testnet
* Support for deploying to Harmony testnet and mainnet
* MetaMask support for Harmony network
* Ability to launch new DAOs
* Ability to install and enable Aragon Apps

# Reward
$10,000 USD in ONE

**Comment by victaphu** [comment]
Hi Giv, I am keen to work on this bounty

**Comment by victaphu** [comment]
Hi Giv, 

Just to note this task is done. 

Here are the relevant github repos changed to host Aragon on Harmony:
UI (update to use personal repo for compile): https://github.com/victaphu/client 
DAO Templates (update to use aragon-wrapper): https://github.com/victaphu/dao-templates
Aragon Apps (update to use aragon-wrapper): https://github.com/victaphu/aragon-apps
Use-Wallet Library (added harmony one config): https://github.com/victaphu/use-wallet
Extension of aragon.js (harmony one config): https://github.com/victaphu/aragon-wrapper
monorepo for Aragon apis: https://github.com/victaphu/aragon.js


Here is a working version of Aragon on the testnet:
http://aragon-harmony.netlify.com/

Best,
Victa

**Comment by givp** [comment]
Winner selected. Congrats and thank you @victaphu !

**Comment by givp** [comment]
Payment complete

https://explorer.harmony.one/tx/0x9a278d5145be12b898a08e47b27bbdade744668a6324ca57ede9481589e07acc
