### ISSUE TITLE
Design cross-shard communication and smart contract functionality

### ISSUE THREAD

**Issue by rlan35** [harmony-one/bounties#85]
# Description
Design of the Harmony's cross-shard communication and smart contract functionalities. The feature should be fully secure against all kinds of attacks so the users asset are not in danger when involved in cross-shard operations such as sending HRC20 across shards or making smart contract calls across shards. The feature should enable the composability of smart contracts across shards.

## Context
Harmony is a sharded blockchain where there are 4 shards each running consensus separately. Currently harmony supports cross-shard ONE token transfer where users can send ONE tokens across shards. Smart contract runs in each individual shards separately as of now and are not able to communicate with smart contracts from other shards. For example, users can not send a HRC20 token that's in shard 0 to shard 1 if the HRC20 contract only lives in shard 0.

Harmony described the initial design idea for the cross-shard smart contract feature here for reference: https://docs.harmony.one/home/general/technology/transactions#cross-shard-smart-contract-transaction. The final design will be worked together by the bounty hunter/grantee and the harmony team.

# Acceptance Criteria
* [ ] Successful deliver of the design of the cross-shard smart contract functionalities with full technical details and specifications, including protocol design change, security analysis, performance considerations, deployment strategies etc.
* [ ] The design should be reviewed by the Harmony core team and improved iteratively until final approval by the Harmony core team.

# Reward
$75k in ONE token

**Comment by givp** [comment]
Moved to [grant application ](https://talk.harmony.one/t/design-cross-shard-communication-and-smart-contract-functionality/4693)
