### ISSUE TITLE
vStatsBot - A monitoring, governance and informative tool for Validators.

### ISSUE THREAD

**Issue by DavidWhicker** [harmony-one/bounties#96]
# Description + Context
vStatsBot’s (Telegram Bot) initial and primary feature is to alert validators within 5 minutes of any missed blocks. This is designed so that the validator can jump onto a problem straight away before it becomes a larger issue that may risk election. The stability of the network is the primary goal here and I truly believe vStatsBot is the first line response.

Other key features of vStatsBot:

- Validator Summary - List of stats for the validator such as stake, keys, bidding power, information on the next election (Time left, slot position, number of keys, bidding power and bounds information), votes yet to be actioned.
- Governance Participation and Reminders - Shows pending votes (Name, Time left, URL) where the validator is yet to participate. This is shown in both the Validator Summary and Votes command. A targeted notification for those who missed the first two alerts will be added.
- Volume Increase Alerts - With the increasing size of db_0 vStatsBot can alert you to the space left at regular intervals and alert you of the automatic size increase. This has helped slow down the number of validators from not singing due to running out of space.
- Blockchain Height Sync Alerts - Quite often I am seeing validators falling behind on their node block heights due to under performing servers. This will alert you to when the drop off is occurring so action can be taken before signing would stop.
- Wallet Summary ( Delegator based ) - The ability to add wallet addresses for scheduled and on command detailed breakdown of staked, unstaked, unclaimed rewards per address. You can also view your most recent claims for tax purposes.
- Election Keys - Shows every possible position on the 900 slots for any number of keys. Especially useful to know where a validator will sit without having to bog the network down in key changes.
- Global Alerts - A message sent out to all participants for any critical alerts.

Future plans:

- Endpoint for Harmony - This will enable Harmony to send one message and it will notify all validators instantly for node updates, news, critical information etc.
- Further expand on the delegators section - Bring informative information to the delegators on their wallets, validator etc.

Screenshots and testimonials on the link below:
https://talk.harmony.one/t/vstatsbot-a-monitoring-governance-and-informative-tool-for-validators/8123

# Acceptance Criteria
* [ ] Uptake by the validator community. Bot is to be used by a large portion of validators to aid in stability of the network and participation. 

# Reward
$24,000 in ONE

**Comment by DylanCkawalec** [comment]
I would like to add this to Harmony's Validator Tool Set. the Application is just about finished. Would you like to see anything before granting? 
I see there's over 80 Active Validators utilizing this tool already. What is your thoughts? Can we push it to gitcoin and David can submit ? 
 @lijiang2087 @sophoah @givp

**Comment by givp** [comment]
This has already been approved: https://talk.harmony.one/t/vstatsbot-a-monitoring-governance-and-informative-tool-for-validators/8123/21
